# Generated by Django 5.2.6 on 2025-09-09 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='实验室名称')),
                ('location', models.CharField(max_length=200, verbose_name='位置')),
                ('capacity', models.PositiveIntegerField(verbose_name='容量')),
                ('equipment', models.TextField(blank=True, verbose_name='设备描述')),
                ('description', models.TextField(blank=True, verbose_name='实验室描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '实验室',
                'verbose_name_plural': '实验室',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='预约日期')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('purpose', models.TextField(verbose_name='使用目的')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '已拒绝'), ('cancelled', '已取消'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('admin_comment', models.TextField(blank=True, verbose_name='管理员备注')),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.laboratory', verbose_name='实验室')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='预约用户')),
            ],
            options={
                'verbose_name': '预约记录',
                'verbose_name_plural': '预约记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='学号')),
                ('phone', models.CharField(max_length=20, verbose_name='电话')),
                ('department', models.CharField(max_length=100, verbose_name='院系')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, '周一'), (1, '周二'), (2, '周三'), (3, '周四'), (4, '周五'), (5, '周六'), (6, '周日')], verbose_name='星期')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('is_available', models.BooleanField(default=True, verbose_name='是否可预约')),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.laboratory', verbose_name='实验室')),
            ],
            options={
                'verbose_name': '时间段',
                'verbose_name_plural': '时间段',
                'ordering': ['laboratory', 'weekday', 'start_time'],
                'unique_together': {('laboratory', 'weekday', 'start_time')},
            },
        ),
    ]
