# Generated by Django 5.2.6 on 2025-09-09 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laboratory',
            options={'ordering': ['category', 'name'], 'verbose_name': '实验室', 'verbose_name_plural': '实验室'},
        ),
        migrations.AddField(
            model_name='laboratory',
            name='category',
            field=models.CharField(choices=[('physics', '物理'), ('chemistry', '化学'), ('biology', '生物'), ('computer', '计算机'), ('engineering', '工程'), ('mathematics', '数学'), ('electronics', '电子'), ('materials', '材料'), ('environmental', '环境'), ('medical', '医学'), ('other', '其他')], default='other', max_length=20, verbose_name='科目分类'),
        ),
    ]
